### PR TITLE
Add new acl permissions

### PR DESCRIPTION
**Pull request by gowrizrh**
Introduces new permissions to manage asynchronous events. This provides more granular control over admin users being able to view / trace / replay logs and update subscriber status.

image

To Do:
- [ ] Integrate new acl resources with `webapi.xml` confirming if there are breaking changes.

### CODE REVIEW

**Review by toddhainsworth — APPROVED** [review]
LGTM!

What're our thoughts on having the resource names match the controller and action? For example `Aligent_AsyncEvents::async_events_logs_replay` could become `Aligent_AsyncEvents::async_events_logs_retry`. If only so it's consistent 🤷

**Comment by gowrizrh** [comment]
@toddhainsworth Thanks, it sounds great to keep it based on the controller name. In this case though the controller should be renamed `Replay` from `Retry` because I didn't pay enough attention when that was created.

**Comment by gowrizrh** [comment]
@toddhainsworth I've renamed the controller and route to `Replay` to align with the replay button and functionality.

**Review by toddhainsworth — APPROVED** [review]

**Comment by toddhainsworth** [comment]
LGTM!

**Pull request merged**
