### PR TITLE
Add integration workflow file

### PR DESCRIPTION
**Pull request by gowrizrh**
As a starting point, I've added a single integration test to ensure we can have Magento Integration tests running in CI.

The test in this PR will place a few dead events and make sure that the relevant queues in RabbitMQ are correctly created.

### CODE REVIEW

**Comment by aligent-lturner** [comment]
@gowrizrh any way to make the various version numbers configurable? i.e. so you could test against different versions of Magento and/or use different container versions?

**Comment by gowrizrh** [comment]
@aligent-lturner Yeah, this is possible in GitHub actions using the matrix workflow. We can create a matrix with multiple os / configs and versions to run the same workflow against all the combinations

**Comment by gowrizrh** [comment]
@aligent-lturner Is this something we want to add to this repository or were you asking in general?

**Comment by aligent-lturner** [comment]
> @aligent-lturner Is this something we want to add to this repository or were you asking in general?

For this one - it's likely to be used across a number of versions, so if we can test across all supported ones, it would be good.

**Comment by gowrizrh** [comment]
Thanks @aligent-lturner, I should be able to write a matrix for 2.4.3-p3 and 2.4.5-p1

Unless you have a list of versions that you'd want to recommend testing against

**Comment by aligent-lturner** [comment]
> Thanks @aligent-lturner, I should be able to write a matrix for 2.4.3-p3 and 2.4.5-p1
> 
> Unless you have a list of versions that you'd want to recommend testing against

Technically speaking, it's only 2.4.4+ that's currently supported.
I'm not sure it's worth getting each individual patch version tested or not, so you could probably just use ranges to get the latest 2.4.4 and 2.4.5 versions (with 2.4.6 to be added in a few months).

**Comment by gowrizrh** [comment]
It will have to be manually defined though so can't use ranges. So if we only want to test against officially supported versions then that's 2.4.5 and 2.4.5-p1.

Or we could define against 2.4.3 and 2.4.5 if that sounds good

**Comment by aligent-lturner** [comment]
> It will have to be manually defined though so can't use ranges. So if we only want to test against officially supported versions then that's 2.4.5 and 2.4.5-p1.
> 
> Or we could define against 2.4.3 and 2.4.5 if that sounds good

Every version from 2.4.4 onwards is still supported? 
Even if it's manually defined, couldn't the defined versions be `>=2.4.4<2.4.5` and `>=2.4.5<2.4.6`?

**Comment by gowrizrh** [comment]
I actually don't know if it'll work with just that. I'll give it a go first

**Comment by gowrizrh** [comment]
@aligent-lturner  I've added a matrix strategy for `>=2.4.4 <2.4.5` and `>=2.4.5 <2.4.6`

All service compatibility data is based from https://github.com/magento/devdocs/blob/master/src/_data/codebase/v2_4/system-requirements.yml#L1

**Review by aligent-lturner — APPROVED** [review]
LGTM - I'd wait for a review from someone from devops before merging though

**Review by krishanthisera — APPROVED** [review]
LGTM

**Pull request merged**
